const wilayas = [
  { number: "01", name: "Adrar" },
  { number: "02", name: "Chlef" },
  { number: "03", name: "Laghouat" },
  { number: "04", name: "Oum El Bouaghi" },
  { number: "05", name: "Batna" },
  { number: "06", name: "Béjaïa" },
  { number: "07", name: "Biskra" },
  { number: "08", name: "Béchar" },
  { number: "09", name: "Blida" },
  { number: "10", name: "Bouira" },
  { number: "11", name: "Tamanrasset" },
  { number: "12", name: "Tébessa" },
  { number: "13", name: "Tlemcen" },
  { number: "14", name: "Tiaret" },
  { number: "15", name: "Tizi Ouzou" },
  { number: "16", name: "Algiers" },
  { number: "17", name: "Djelfa" },
  { number: "18", name: "Jijel" },
  { number: "19", name: "Sétif" },
  { number: "20", name: "Saïda" },
  { number: "21", name: "Skikda" },
  { number: "22", name: "Sidi Bel Abbès" },
  { number: "23", name: "Annaba" },
  { number: "24", name: "Guelma" },
  { number: "25", name: "Constantine" },
  { number: "26", name: "Médéa" },
  { number: "27", name: "Mostaganem" },
  { number: "28", name: "M'Sila" },
  { number: "29", name: "Mascara" },
  { number: "30", name: "Ouargla" },
  { number: "31", name: "Oran" },
  { number: "32", name: "El Bayadh" },
  { number: "33", name: "Illizi" },
  { number: "34", name: "Bordj Bou Arréridj" },
  { number: "35", name: "Boumerdès" },
  { number: "36", name: "El Tarf" },
  { number: "37", name: "Tindouf" },
  { number: "38", name: "Tissemsilt" },
  { number: "39", name: "El Oued" },
  { number: "40", name: "Khenchela" },
  { number: "41", name: "Souk Ahras" },
  { number: "42", name: "Tipaza" },
  { number: "43", name: "Mila" },
  { number: "44", name: "Aïn Defla" },
  { number: "45", name: "Naâma" },
  { number: "46", name: "Aïn Témouchent" },
  { number: "47", name: "Ghardaïa" },
  { number: "48", name: "Relizane" },
  { number: "49", name: "Timimoun" },
  { number: "50", name: "Bordj Badji Mokhtar" },
  { number: "51", name: "Ouled Djellal" },
  { number: "52", name: "Béni Abbès" },
  { number: "53", name: "In Salah" },
  { number: "54", name: "In Guezzam" },
  { number: "55", name: "Touggourt" },
  { number: "56", name: "Djanet" },
  { number: "57", name: "El Meghaier" },
  { number: "58", name: "El Meniaa" },
];

export default wilayas;